AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.3

Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 100
Metrics/MethodLength:
  Max: 80
Metrics/BlockLength:
  Max: 70
Metrics/ClassLength:
  Max: 150
Metrics/ParameterLists:
  Max: 10
Layout/AlignParameters:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 7
