assets:
  rubygems.yml: zerocracy/home#assets/rubygems.yml
install: |-
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
release:
  script: |-
    bundle install
    sudo rvm repair wrappers
    zold --version
    rake --quiet
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" zold-stress.gemspec
    git add zold-stress.gemspec
    git commit -m "Version set to ${tag}"
    gem build zold-stress.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
  commanders:
  - yegor256
architect:
- yegor256
merge:
  commanders: []
  script: |-
    bundle install
    rake --quiet
deploy: {}
